name: postory_theme
description: A new Flutter package project.
version: 0.0.1
homepage: https://postory-app.github.io/theme/
repository: https://github.com/postory-app/theme

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  dynamic_color: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/explore/
    - images/payment/
    - images/pocoin/
    - images/virtual_address/
    - lotties/
    - svgs/

  fonts:
    - family: POSTORY
      fonts:
        - asset: fonts/POSTORY.ttf
